<?php

namespace App\Services;

use App\Models\BlogPost;
use App\Models\Destination;
use App\Models\Page;
use App\Models\ManagerList;
use App\Models\TourCategory;
use App\Models\TourPackage;
use Illuminate\Support\Facades\File;

/**
 * Sitemap.xml generator.
 *
 * Mirrors the SEO behaviour of the legacy kizza-tours platform: builds a single
 * flat urlset that lists static routes plus published Tours, Destinations,
 * Pages and Blog posts — each with a priority / changefreq / lastmod — while
 * honouring each entity's `no_robots` (noindex) flag so admins can keep
 * specific items out of Google's index.
 */
class SitemapGenerator
{
    /**
     * Static (non-model) URLs. Priority mirrors the kizza reference:
     * home is the highest, then listing pages.
     */
    protected static function staticUrls(): array
    {
        return [
            ['loc' => route('home'),                'priority' => '1.0', 'changefreq' => 'weekly',   'lastmod' => static::globalLastmod()],
            ['loc' => route('tours.index'),         'priority' => '0.9', 'changefreq' => 'weekly',   'lastmod' => static::globalLastmod()],
            ['loc' => route('destinations.index'),  'priority' => '0.8', 'changefreq' => 'weekly',   'lastmod' => static::globalLastmod()],
            ['loc' => route('blog.index'),          'priority' => '0.7', 'changefreq' => 'weekly',   'lastmod' => static::globalLastmod()],
            ['loc' => route('accommodations.index'),'priority' => '0.6', 'changefreq' => 'monthly',  'lastmod' => static::globalLastmod()],
        ];
    }

    /**
     * Legacy/static URLs already live on the production domain
     * (https://www.afrovertextours.com). These pages are NOT represented in the
     * Laravel DB yet, but the folders still exist on the live server, so their
     * URLs are preserved here so /sitemap.xml (generated by this app) keeps
     * serving every historically-indexed location from one single sitemap.
     *
     * @return array<int, array{loc: string, lastmod: string, changefreq: string, priority: string}>
     */
    protected static function liveUrls(): array
    {
        $base = 'https://www.afrovertextours.com';

        return [
            ['loc' => "$base/",                                                                              'lastmod' => '2024-07-16', 'changefreq' => 'weekly',  'priority' => '1.0'],
            ['loc' => "$base/contact.html",                                                                  'lastmod' => '2024-07-16', 'changefreq' => 'monthly', 'priority' => '1.0'],
            ['loc' => "$base/tanzania/serengeti/",                                                           'lastmod' => '2024-07-17', 'changefreq' => 'weekly',  'priority' => '1.0'],
            ['loc' => "$base/tanzania/serengeti-wildebeest-migration/",                                      'lastmod' => '2024-07-17', 'changefreq' => 'weekly',  'priority' => '1.0'],

            // ── Kilimanjaro ────────────────────────────────────────────────────
            ['loc' => "$base/tanzania/kilimanjaro/",                                                         'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '1.00'],
            ['loc' => "$base/tanzania/kilimanjaro/kilimanjaro-climbing-routes.html",                          'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.80'],
            ['loc' => "$base/tanzania/kilimanjaro/kilimanjaro-marangu-route.html",                            'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.80'],
            ['loc' => "$base/tanzania/kilimanjaro/kilimanjaro-machame-route.html",                            'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.80'],
            ['loc' => "$base/tanzania/kilimanjaro/kilimanjaro-lemosho-route.html",                            'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.80'],
            ['loc' => "$base/tanzania/kilimanjaro/kilimanjaro-rongai-route.html",                             'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.80'],
            ['loc' => "$base/tanzania/kilimanjaro/kilimanjaro-northern-circuit-route.html",                   'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.80'],
            ['loc' => "$base/tanzania/kilimanjaro/kilimanjaro-umbwe-route.html",                              'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.80'],
            ['loc' => "$base/tanzania/kilimanjaro/kilimanjaro-climbing-tours.html",                           'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.80'],
            ['loc' => "$base/tanzania/kilimanjaro/5-days-kilimanjaro-tours.html",                             'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.80'],
            ['loc' => "$base/tanzania/kilimanjaro/6-days-kilimanjaro-tours.html",                             'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.80'],
            ['loc' => "$base/tanzania/kilimanjaro/7-days-kilimanjaro-tours.html",                             'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.80'],
            ['loc' => "$base/tanzania/kilimanjaro/8-days-kilimanjaro-tours.html",                             'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.80'],
            ['loc' => "$base/tanzania/kilimanjaro/9-days-kilimanjaro-tours.html",                             'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.80'],
            ['loc' => "$base/tanzania/kilimanjaro/kilimanjaro-special-tours.html",                            'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.80'],
            ['loc' => "$base/tanzania/kilimanjaro/kilimanjaro-full-moon-tours.html",                          'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.80'],
            ['loc' => "$base/tanzania/kilimanjaro/kilimanjaro-bike-trekking-tour.html",                       'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.80'],
            ['loc' => "$base/tanzania/kilimanjaro/kilimanjaro-christmas-tours.html",                          'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.80'],
            ['loc' => "$base/tanzania/kilimanjaro/kilimanjaro-new-year-eve.html",                             'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.80'],
            ['loc' => "$base/tanzania/kilimanjaro/kilimanjaro-gallery.html",                                 'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.80'],
            ['loc' => "$base/tanzania/kilimanjaro/contact.html",                                             'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.80'],
            ['loc' => "$base/tanzania/kilimanjaro/kilimanjaro-packing-list.html",                             'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.80'],
            ['loc' => "$base/tanzania/kilimanjaro/kilimanjaro-climbing-price.html",                           'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.80'],
            ['loc' => "$base/tanzania/kilimanjaro/kilimanjaro-meals.html",                                   'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.80'],
            ['loc' => "$base/tanzania/kilimanjaro/kilimanjaro-climbing-accommodation.html",                   'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.80'],
            ['loc' => "$base/tanzania/kilimanjaro/accommodation-before-and-after-kilimanjaro-climbing.html",  'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.80'],
            ['loc' => "$base/tanzania/kilimanjaro/best-time-for-kilimanjaro-climbing.html",                   'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.80'],
            ['loc' => "$base/tanzania/kilimanjaro/kilimanjaro-nearby-airport.html",                           'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.80'],
            ['loc' => "$base/tanzania/kilimanjaro/kilimanjaro-kosovo-camp.html",                              'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.80'],
            ['loc' => "$base/tanzania/kilimanjaro/climbing-kilimanjaro.html",                                 'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/kilimanjaro/10-days-kilimanjaro-tours.html",                            'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/kilimanjaro/5-days-kilimanjaro-climbing-marangu-route-tour.html",       'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/kilimanjaro/6-days-kilimanjaro-climbing-marangu-route-tour.html",       'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/kilimanjaro/6-days-kilimanjaro-climbing-machame-route-tour.html",       'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/kilimanjaro/7-days-kilimanjaro-climbing-machame-route-tour.html",       'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/kilimanjaro/6-days-kilimanjaro-climbing-lemosho-route-tour.html",       'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/kilimanjaro/7-days-kilimanjaro-climbing-lemosho-route-tour.html",       'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/kilimanjaro/8-days-kilimanjaro-climbing-lemosho-route-tour.html",       'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/kilimanjaro/5-days-kilimanjaro-climbing-rongai-route-tour.html",        'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/kilimanjaro/6-days-kilimanjaro-climbing-rongai-route-tour.html",        'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/kilimanjaro/7-days-kilimanjaro-climbing-rongai-route-tour.html",        'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/kilimanjaro/8-days-kilimanjaro-climbing-northern-circuit-route-tour.html", 'lastmod' => '2024-11-27', 'changefreq' => 'weekly', 'priority' => '0.64'],
            ['loc' => "$base/tanzania/kilimanjaro/9-days-kilimanjaro-climbing-northern-circuit-route-tour.html", 'lastmod' => '2024-11-27', 'changefreq' => 'weekly', 'priority' => '0.64'],
            ['loc' => "$base/tanzania/kilimanjaro/6-days-kilimanjaro-climbing-umbwe-route-tour.html",         'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/kilimanjaro/7-days-kilimanjaro-climbing-umbwe-route-tour.html",         'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/kilimanjaro/6-days-kilimanjaro-climbing-londorosi-route-tour.html",     'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/kilimanjaro/7-days-kilimanjaro-climbing-londorosi-route-tour.html",     'lastmod' => '2024-11-27', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/kilimanjaro/5-days-marangu-route-kilimanjaro-bike-cycling-tour.html",   'lastmod' => '2026-06-17', 'changefreq' => 'weekly',  'priority' => '0.64'],

            // ── Safari Tours ───────────────────────────────────────────────────
            ['loc' => "$base/tanzania/safari-tours/",                                                        'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '1.00'],
            ['loc' => "$base/tanzania/safari-tours/tanzania-group-safaris.html",                              'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.80'],
            ['loc' => "$base/tanzania/safari-tours/tanzania-private-safaris.html",                            'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.80'],
            ['loc' => "$base/tanzania/safari-tours/contact.html",                                             'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.80'],
            ['loc' => "$base/tanzania/safari-tours/tanzania-safari.html",                                    'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/safari-tours/private-lodge-safaris.html",                               'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/safari-tours/index.html",                                              'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.51'],
            ['loc' => "$base/tanzania/safari-tours/tanzania-luxury-lodge-safaris.html",                       'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.51'],
            ['loc' => "$base/tanzania/safari-tours/tanzania-mid-range-lodge-safaris.html",                   'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.51'],

            // Group-safari monthly departures (batch 1)
            ['loc' => "$base/tanzania/safari-tours/january-1-tanzania-group-safaris-departures.html",        'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/safari-tours/february-1-tanzania-group-safaris-departures.html",       'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/safari-tours/march-1-tanzania-group-safaris-departures.html",          'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/safari-tours/april-1-tanzania-group-safaris-departures.html",          'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/safari-tours/may-1-tanzania-group-safaris-departures.html",            'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/safari-tours/june-1-tanzania-group-safaris-departures.html",           'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/safari-tours/july-1-tanzania-group-safaris-departures.html",           'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/safari-tours/august-1-tanzania-group-safaris-departures.html",         'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/safari-tours/september-1-tanzania-group-safaris-departures.html",      'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/safari-tours/october-1-tanzania-group-safaris-departures.html",        'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/safari-tours/november-1-tanzania-group-safaris-departures.html",       'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/safari-tours/december-1-tanzania-group-safaris-departures.html",       'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.64'],

            // Group-safari monthly departures (batch 2)
            ['loc' => "$base/tanzania/safari-tours/january-2-tanzania-group-safaris-departures.html",        'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/safari-tours/february-2-tanzania-group-safaris-departures.html",       'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/safari-tours/march-2-tanzania-group-safaris-departures.html",          'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/safari-tours/april-2-tanzania-group-safaris-departures.html",          'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/safari-tours/may-2-tanzania-group-safaris-departures.html",            'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/safari-tours/june-2-tanzania-group-safaris-departures.html",           'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/safari-tours/july-2-tanzania-group-safaris-departures.html",           'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/safari-tours/august-2-tanzania-group-safaris-departures.html",         'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/safari-tours/september-2-tanzania-group-safaris-departures.html",      'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/safari-tours/october-2-tanzania-group-safaris-departures.html",        'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/safari-tours/november-2-tanzania-group-safaris-departures.html",       'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.64'],
            ['loc' => "$base/tanzania/safari-tours/december-2-tanzania-group-safaris-departures.html",       'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.64'],

            // Lodge safaris by length
            ['loc' => "$base/tanzania/safari-tours/2-days-tanzania-mid-range-lodge-safaris.html",            'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.51'],
            ['loc' => "$base/tanzania/safari-tours/2-days-tanzania-luxury-lodge-safaris.html",               'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.51'],
            ['loc' => "$base/tanzania/safari-tours/3-days-tanzania-mid-range-lodge-safaris.html",            'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.51'],
            ['loc' => "$base/tanzania/safari-tours/3-days-tanzania-luxury-lodge-safaris.html",               'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.51'],
            ['loc' => "$base/tanzania/safari-tours/4-days-tanzania-mid-range-lodge-safaris.html",            'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.51'],
            ['loc' => "$base/tanzania/safari-tours/4-days-tanzania-luxury-lodge-safaris.html",               'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.51'],
            ['loc' => "$base/tanzania/safari-tours/5-days-tanzania-mid-range-lodge-safaris.html",            'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.51'],
            ['loc' => "$base/tanzania/safari-tours/5-days-tanzania-luxury-lodge-safaris.html",               'lastmod' => '2024-11-28', 'changefreq' => 'weekly',  'priority' => '0.51'],
        ];
    }

    /**
     * Newest content on the site is used as the lastmod for the static pages,
     * so search engines see the sitemap as fresh.
     */
    protected static function globalLastmod(): string
    {
        $latest = collect([
            TourPackage::where('status', 'published')->max('updated_at'),
            Destination::max('updated_at'),
            Page::where('status', 'published')->max('updated_at'),
            ManagerList::where('status', 'published')->max('updated_at'),
            BlogPost::where('status', 'published')->max('updated_at'),
        ])->filter()->max();

        return $latest ? \Illuminate\Support\Carbon::parse($latest)->format('Y-m-d') : date('Y-m-d');
    }

    /**
     * Every public URL entry as [loc, lastmod, changefreq, priority].
     */
    public static function entries(): array
    {
        $entries = array_merge(static::liveUrls(), static::staticUrls());

        foreach (TourPackage::where('status', 'published')
                     ->where('no_robots', false)
                     ->get() as $tour) {
            $entries[] = [
                'loc'       => route('tour.show', $tour->slug),
                'priority'  => '0.8',
                'changefreq'=> 'weekly',
                'lastmod'   => $tour->updated_at?->format('Y-m-d') ?: date('Y-m-d'),
            ];
        }

        // Only the public listing categories produce /{slug} URLs. Grouped
        // taxonomy rows (country/region/tour_type/duration) are tour-form
        // dropdown options and must not add low-value landing pages
        // (/private, /1-day, …) to the sitemap.
        foreach (TourCategory::where('type', TourCategory::TYPE_CATEGORY)
                     ->where('no_robots', false)
                     ->whereHas('tourPackages', fn ($q) => $q->where('status', 'published'))
                     ->get() as $category) {
            $entries[] = [
                'loc'       => route('tours.category', $category->slug),
                'priority'  => '0.7',
                'changefreq'=> 'weekly',
                'lastmod'   => $category->updated_at?->format('Y-m-d') ?: date('Y-m-d'),
            ];
        }

        foreach (Destination::whereNotNull('slug')->where('slug', '!=', '')->get() as $dest) {
            $entries[] = [
                'loc'       => route('destination.show', $dest->slug),
                'priority'  => '0.6',
                'changefreq'=> 'monthly',
                'lastmod'   => $dest->updated_at?->format('Y-m-d') ?: date('Y-m-d'),
            ];
        }

        foreach (Page::where('status', 'published')
                     ->where('no_robots', false)
                     ->get() as $page) {
            $entries[] = [
                'loc'       => route('page.show', $page->slug),
                'priority'  => '0.6',
                'changefreq'=> 'monthly',
                'lastmod'   => $page->updated_at?->format('Y-m-d') ?: date('Y-m-d'),
            ];
        }

        foreach (ManagerList::where('status', 'published')->where('no_robots', false)->get() as $managerList) {
            $hasSelection = $managerList->content_type === 'tours'
                ? $managerList->scopedTours()->exists()
                : ! empty($managerList->page_ids) && Page::where('status', 'published')->where('no_robots', false)
                    ->whereNotIn('slug', Page::siteInfoSlugs())->whereIn('id', $managerList->page_ids)->exists();
            if (! $hasSelection) {
                continue;
            }
            $entries[] = [
                'loc' => route('manager-lists.show', $managerList->slug),
                'priority' => '0.7',
                'changefreq' => 'weekly',
                'lastmod' => $managerList->updated_at?->format('Y-m-d') ?: date('Y-m-d'),
            ];
        }

        foreach (BlogPost::where('status', 'published')
                     ->where('no_robots', false)
                     ->get() as $post) {
            $entries[] = [
                'loc'       => route('blog.show', $post->slug),
                'priority'  => '0.6',
                'changefreq'=> 'monthly',
                'lastmod'   => $post->updated_at?->format('Y-m-d') ?: date('Y-m-d'),
            ];
        }

        return $entries;
    }

    /**
     * Build the full sitemap.xml string.
     */
    public static function build(): string
    {
        $entries = static::entries();

        $xml = '<?xml version="1.0" encoding="UTF-8"?>' . "\n";
        $xml .= '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' . "\n";

        foreach ($entries as $e) {
            $xml .= "  <url>\n";
            $xml .= '    <loc>' . htmlspecialchars($e['loc'], ENT_XML1, 'UTF-8') . "</loc>\n";
            $xml .= '    <lastmod>' . htmlspecialchars($e['lastmod'], ENT_XML1, 'UTF-8') . "</lastmod>\n";
            $xml .= '    <changefreq>' . htmlspecialchars($e['changefreq'], ENT_XML1, 'UTF-8') . "</changefreq>\n";
            $xml .= '    <priority>' . htmlspecialchars($e['priority'], ENT_XML1, 'UTF-8') . "</priority>\n";
            $xml .= "  </url>\n";
        }

        $xml .= '</urlset>' . "\n";
        return $xml;
    }

    /**
     * Write sitemap.xml into the web root (public/). Returns true on success.
     */
    public static function generate(): bool
    {
        return File::put(public_path('sitemap.xml'), static::build()) !== false;
    }

    /**
     * Path of the generated static sitemap file (useful for the admin UI).
     */
    public static function filePath(): string
    {
        return public_path('sitemap.xml');
    }
}
