{{--
    Dedicated tours-listing pagination partial.

    Receives:
        - $paginator  (Illuminate\Contracts\Pagination\LengthAwarePaginator)

    Renders nothing when a single page of results exists. Page URLs are
    generated by the paginator itself ($paginator->url($page)), so every
    active filter/sort parameter is preserved via withQueryString().
--}}
@php
    $paginationCurrent = $paginator->currentPage();
    $paginationLast    = $paginator->lastPage();

    // Smart window: current page ±2, always showing first & last page,
    // one ellipsis per skipped group, all pages when seven or fewer.
    $windowStart = max(1, min($paginationCurrent - 2, max(1, $paginationLast - 4)));
    $windowEnd   = min($paginationLast, $windowStart + 4);
    $desktopPaginationPages = range($windowStart, $windowEnd);
@endphp

@if ($paginator->hasPages())
    <nav class="sfb-pagination" aria-label="Tour results pages">
        @if ($paginator->onFirstPage())
            <span class="sfb-page-btn sfb-page-btn--wide is-disabled" aria-disabled="true">
                <span aria-hidden="true">&lsaquo;</span>
                <span class="sfb-page-btn__word">Prev</span>
            </span>
        @else
            <a class="sfb-page-btn sfb-page-btn--wide" href="{{ $paginator->previousPageUrl() }}" rel="prev" data-sfb-page-link aria-label="Go to previous page">
                <span aria-hidden="true">&lsaquo;</span>
                <span class="sfb-page-btn__word">Prev</span>
            </a>
        @endif

        <div class="sfb-pagination__pages sfb-pagination__pages--desktop" aria-label="Page numbers">
            @if (! in_array(1, $desktopPaginationPages, true))
                <a class="sfb-page-btn" href="{{ $paginator->url(1) }}" data-sfb-page-link aria-label="Go to page 1">1</a>
                @if ($windowStart > 2)
                    <span class="sfb-page-ellipsis" aria-hidden="true">&hellip;</span>
                @endif
            @endif

            @foreach ($desktopPaginationPages as $pageNumber)
                @if ($pageNumber === $paginationCurrent)
                    <span class="sfb-page-btn is-active" aria-current="page" aria-label="Current page, page {{ $pageNumber }}">{{ $pageNumber }}</span>
                @else
                    <a class="sfb-page-btn" href="{{ $paginator->url($pageNumber) }}" data-sfb-page-link aria-label="Go to page {{ $pageNumber }}">{{ $pageNumber }}</a>
                @endif
            @endforeach

            @if (! in_array($paginationLast, $desktopPaginationPages, true))
                @if ($windowEnd < $paginationLast - 1)
                    <span class="sfb-page-ellipsis" aria-hidden="true">&hellip;</span>
                @endif
                <a class="sfb-page-btn" href="{{ $paginator->url($paginationLast) }}" data-sfb-page-link aria-label="Go to page {{ $paginationLast }}">{{ $paginationLast }}</a>
            @endif
        </div>

        {{-- Compact "Page X of Y" summary for small screens --}}
        <div class="sfb-pagination__summary">
            Page {{ $paginationCurrent }} of {{ $paginationLast }}
        </div>

        @if ($paginator->hasMorePages())
            <a class="sfb-page-btn sfb-page-btn--wide" href="{{ $paginator->nextPageUrl() }}" rel="next" data-sfb-page-link aria-label="Go to next page">
                <span class="sfb-page-btn__word">Next</span>
                <span aria-hidden="true">&rsaquo;</span>
            </a>
        @else
            <span class="sfb-page-btn sfb-page-btn--wide is-disabled" aria-disabled="true">
                <span class="sfb-page-btn__word">Next</span>
                <span aria-hidden="true">&rsaquo;</span>
            </span>
        @endif
    </nav>
@endif
