@php
    $pricingService = new \App\Services\PricingService();
    $levelCatalog = config('tour.level_catalog');
    $multiDayCategories = $pricingService->multiDayCategories();
    $singleDayLevel = $pricingService->singleDayLevel();
    $predefinedCosts = config('tour.predefined_costs');
    $basisLabels = $pricingService->chargingBasisLabels();
    $basisHelp = $pricingService->chargingBasisHelp();

    $currentSource = old('pricing_source', $tourPackage->pricing_source ?? 'none');
    $currentDuration = old('package_duration_type', $tourPackage->package_duration_type ?? 'multi_day');
    $currentCategory = old('package_category', $tourPackage->package_category ?? ($multiDayCategories[0] ?? 'LUXURY'));
    $currentTourType = old('tour_type', $tourPackage->tour_type ?? '');
    $currentManualCurrency = old('manual_currency', $tourPackage->currency ?? 'USD');

    $manualRowsExisting = [];
    if ($tourPackage && $tourPackage->relationLoaded('packagePrices')) {
        foreach ($tourPackage->packagePrices->sortBy('season_code')->sortBy('level_key') as $pp) {
            $manualRowsExisting[] = [
                'level_key'   => $pp->level_key,
                'season_code' => $pp->season_code,
                'price_2p'    => $pp->price_2p,
                'price_4p'    => $pp->price_4p,
                'price_6p'    => $pp->price_6p,
            ];
        }
    }
    $manualRows = old('manual_prices', $manualRowsExisting);
    $existingCalculatorPayload = old('calculator_payload', $existingCalculationPayload ?? null);
@endphp

<div class="card mb-3">
    <div class="card-body">
        <h5 class="card-title">Pricing
            <span class="text-muted fw-normal fs-6">(new-system pricing &mdash; manually entered or generated by the calculator)</span>
        </h5>

        @if ($tourPackage && ($tourPackage->pricing_source ?? 'legacy') === 'legacy')
            @include('admin.tour-packages.partials.pricing.legacy', [
                'tourPackage' => $tourPackage,
            ])
        @endif

        {{-- Source selector --}}
        <div class="row mb-3" id="pricing-source-row">
            <label class="col-sm-2 col-form-label">Pricing Source</label>
            <div class="col-sm-10">
                <div class="d-flex flex-wrap gap-3">
                    <div class="form-check form-check-inline">
                        <input class="form-check-input pricing-source" type="radio" name="pricing_source"
                               id="pricing-source-none" value="none"
                               {{ $currentSource === 'none' ? 'checked' : '' }}>
                        <label class="form-check-label" for="pricing-source-none">None</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input pricing-source" type="radio" name="pricing_source"
                               id="pricing-source-manual" value="manual"
                               {{ $currentSource === 'manual' ? 'checked' : '' }}>
                        <label class="form-check-label" for="pricing-source-manual">Manual entry</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input pricing-source" type="radio" name="pricing_source"
                               id="pricing-source-calculator" value="calculator"
                               {{ $currentSource === 'calculator' ? 'checked' : '' }}>
                        <label class="form-check-label" for="pricing-source-calculator">Price calculator</label>
                    </div>
                </div>
                <small class="form-text text-muted">
                    Manual entry stores one price grid (per season &times; per level). The calculator derives prices from cost items server-side. Existing SILVER / GOLD / PLATINUM pricing stays untouched either way.
                </small>
            </div>
        </div>

        {{-- Duration / tour type / category (relevant for manual + calculator) --}}
        <div class="pricing-config-row" id="pricing-config-row">
            <div class="row mb-3">
                <label class="col-sm-2 col-form-label">Duration Type</label>
                <div class="col-sm-10">
                    <select name="package_duration_type" id="pricing-duration" class="form-select">
                        <option value="multi_day" {{ $currentDuration === 'multi_day' ? 'selected' : '' }}>Multi-day</option>
                        <option value="single_day" {{ $currentDuration === 'single_day' ? 'selected' : '' }}>Single-day</option>
                    </select>
                </div>
            </div>

            <div class="row mb-3 pricing-multi-day-only">
                <label class="col-sm-2 col-form-label">Package Category</label>
                <div class="col-sm-10">
                    <select name="package_category" id="pricing-category" class="form-select">
                        <option value="">-- Select category --</option>
                        @foreach ($levelCatalog as $categoryKey => $categoryMeta)
                            @if ($categoryKey === 'SINGLE_DAY') @continue @endif
                            <option value="{{ $categoryKey }}" {{ $currentCategory === $categoryKey ? 'selected' : '' }}>
                                {{ $categoryMeta['label'] }}
                            </option>
                        @endforeach
                    </select>
                    <small class="form-text text-muted">Maps to the LUXURY / MID_RANGE / BUDGET product tiers.</small>
                </div>
            </div>

            <div class="row mb-3 pricing-calculator-only">
                <label class="col-sm-2 col-form-label">Tour Type</label>
                <div class="col-sm-10">
                    <select name="tour_type" id="pricing-tour-type" class="form-select">
                        <option value="">-- Select tour type --</option>
                        @foreach (array_keys($predefinedCosts) as $typeKey)
                            <option value="{{ $typeKey }}" {{ $currentTourType === $typeKey ? 'selected' : '' }}>{{ $typeKey }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
        </div>

        {{-- Panes --}}
        @include('admin.tour-packages.partials.pricing.manual', [
            'manualRows' => $manualRows,
            'currentManualCurrency' => $currentManualCurrency,
            'basisHelp' => $basisHelp,
        ])

        @include('admin.tour-packages.partials.pricing.calculator', [
            'existingCalculatorPayload' => $existingCalculatorPayload,
            'currentDuration' => $currentDuration,
            'currentCategory' => $currentCategory,
            'currentTourType' => $currentTourType,
            'predefinedCosts' => $predefinedCosts,
        ])

        {{-- Preview target (calculator preview responses land here) --}}
        <div id="pricing-preview-target"></div>
    </div>
</div>

@include('admin.tour-packages.partials.pricing.scripts', [
    'levelCatalog' => $levelCatalog,
    'predefinedCosts' => $predefinedCosts,
    'basisLabels' => $basisLabels,
    'singleDayLevel' => $singleDayLevel,
    'manualRows' => $manualRows,
    'existingCalculatorPayload' => $existingCalculatorPayload,
    'currentSource' => $currentSource,
    'currentDuration' => $currentDuration,
    'currentCategory' => $currentCategory,
    'currentTourType' => $currentTourType,
])

<template id="pricing-cost-item-row-template">
    @include('admin.tour-packages.partials.pricing.cost-item-row', [
        'item' => [],
        'itemIndex' => '__ROW__',
        'basisLabels' => $basisLabels,
        'basisHelp' => $basisHelp,
    ])
</template>