<?php
    $pricingService = new \App\Services\PricingService();
    $levelCatalog = config('tour.level_catalog');
    $multiDayCategories = $pricingService->multiDayCategories();
    $singleDayLevel = $pricingService->singleDayLevel();
    $predefinedCosts = config('tour.predefined_costs');
    $basisLabels = $pricingService->chargingBasisLabels();
    $basisHelp = $pricingService->chargingBasisHelp();

    $currentSource = old('pricing_source', $tourPackage->pricing_source ?? 'none');
    $currentDuration = old('package_duration_type', $tourPackage->package_duration_type ?? 'multi_day');
    $currentCategory = old('package_category', $tourPackage->package_category ?? ($multiDayCategories[0] ?? 'LUXURY'));
    $currentTourType = old('tour_type', $tourPackage->tour_type ?? '');
    $currentManualCurrency = old('manual_currency', $tourPackage->currency ?? 'USD');

    $manualRowsExisting = [];
    if ($tourPackage && $tourPackage->relationLoaded('packagePrices')) {
        foreach ($tourPackage->packagePrices->sortBy('season_code')->sortBy('level_key') as $pp) {
            $manualRowsExisting[] = [
                'level_key'   => $pp->level_key,
                'season_code' => $pp->season_code,
                'price_2p'    => $pp->price_2p,
                'price_4p'    => $pp->price_4p,
                'price_6p'    => $pp->price_6p,
            ];
        }
    }
    $manualRows = old('manual_prices', $manualRowsExisting);
    $existingCalculatorPayload = old('calculator_payload', $existingCalculationPayload ?? null);
?>

<div class="card mb-3">
    <div class="card-body">
        <h5 class="card-title">Pricing
            <span class="text-muted fw-normal fs-6">(new-system pricing &mdash; manually entered or generated by the calculator)</span>
        </h5>

        <?php if($tourPackage && ($tourPackage->pricing_source ?? 'legacy') === 'legacy'): ?>
            <?php echo $__env->make('admin.tour-packages.partials.pricing.legacy', [
                'tourPackage' => $tourPackage,
            ], \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
        <?php endif; ?>

        
        <div class="row mb-3" id="pricing-source-row">
            <label class="col-sm-2 col-form-label">Pricing Source</label>
            <div class="col-sm-10">
                <div class="d-flex flex-wrap gap-3">
                    <div class="form-check form-check-inline">
                        <input class="form-check-input pricing-source" type="radio" name="pricing_source"
                               id="pricing-source-none" value="none"
                               <?php echo e($currentSource === 'none' ? 'checked' : ''); ?>>
                        <label class="form-check-label" for="pricing-source-none">None</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input pricing-source" type="radio" name="pricing_source"
                               id="pricing-source-manual" value="manual"
                               <?php echo e($currentSource === 'manual' ? 'checked' : ''); ?>>
                        <label class="form-check-label" for="pricing-source-manual">Manual entry</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input pricing-source" type="radio" name="pricing_source"
                               id="pricing-source-calculator" value="calculator"
                               <?php echo e($currentSource === 'calculator' ? 'checked' : ''); ?>>
                        <label class="form-check-label" for="pricing-source-calculator">Price calculator</label>
                    </div>
                </div>
                <small class="form-text text-muted">
                    Manual entry stores one price grid (per season &times; per level). The calculator derives prices from cost items server-side. Existing SILVER / GOLD / PLATINUM pricing stays untouched either way.
                </small>
            </div>
        </div>

        
        <div class="pricing-config-row" id="pricing-config-row">
            <div class="row mb-3">
                <label class="col-sm-2 col-form-label">Duration Type</label>
                <div class="col-sm-10">
                    <select name="package_duration_type" id="pricing-duration" class="form-select">
                        <option value="multi_day" <?php echo e($currentDuration === 'multi_day' ? 'selected' : ''); ?>>Multi-day</option>
                        <option value="single_day" <?php echo e($currentDuration === 'single_day' ? 'selected' : ''); ?>>Single-day</option>
                    </select>
                </div>
            </div>

            <div class="row mb-3 pricing-multi-day-only">
                <label class="col-sm-2 col-form-label">Package Category</label>
                <div class="col-sm-10">
                    <select name="package_category" id="pricing-category" class="form-select">
                        <option value="">-- Select category --</option>
                        <?php $__currentLoopData = $levelCatalog; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $categoryKey => $categoryMeta): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                            <?php if($categoryKey === 'SINGLE_DAY'): ?> <?php continue; ?> <?php endif; ?>
                            <option value="<?php echo e($categoryKey); ?>" <?php echo e($currentCategory === $categoryKey ? 'selected' : ''); ?>>
                                <?php echo e($categoryMeta['label']); ?>

                            </option>
                        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                    </select>
                    <small class="form-text text-muted">Maps to the LUXURY / MID_RANGE / BUDGET product tiers.</small>
                </div>
            </div>

            <div class="row mb-3 pricing-calculator-only">
                <label class="col-sm-2 col-form-label">Tour Type</label>
                <div class="col-sm-10">
                    <select name="tour_type" id="pricing-tour-type" class="form-select">
                        <option value="">-- Select tour type --</option>
                        <?php $__currentLoopData = array_keys($predefinedCosts); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $typeKey): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                            <option value="<?php echo e($typeKey); ?>" <?php echo e($currentTourType === $typeKey ? 'selected' : ''); ?>><?php echo e($typeKey); ?></option>
                        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                    </select>
                </div>
            </div>
        </div>

        
        <?php echo $__env->make('admin.tour-packages.partials.pricing.manual', [
            'manualRows' => $manualRows,
            'currentManualCurrency' => $currentManualCurrency,
            'basisHelp' => $basisHelp,
        ], \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>

        <?php echo $__env->make('admin.tour-packages.partials.pricing.calculator', [
            'existingCalculatorPayload' => $existingCalculatorPayload,
            'currentDuration' => $currentDuration,
            'currentCategory' => $currentCategory,
            'currentTourType' => $currentTourType,
            'predefinedCosts' => $predefinedCosts,
        ], \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>

        
        <div id="pricing-preview-target"></div>
    </div>
</div>

<?php echo $__env->make('admin.tour-packages.partials.pricing.scripts', [
    'levelCatalog' => $levelCatalog,
    'predefinedCosts' => $predefinedCosts,
    'basisLabels' => $basisLabels,
    'singleDayLevel' => $singleDayLevel,
    'manualRows' => $manualRows,
    'existingCalculatorPayload' => $existingCalculatorPayload,
    'currentSource' => $currentSource,
    'currentDuration' => $currentDuration,
    'currentCategory' => $currentCategory,
    'currentTourType' => $currentTourType,
], \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>

<template id="pricing-cost-item-row-template">
    <?php echo $__env->make('admin.tour-packages.partials.pricing.cost-item-row', [
        'item' => [],
        'itemIndex' => '__ROW__',
        'basisLabels' => $basisLabels,
        'basisHelp' => $basisHelp,
    ], \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
</template><?php /**PATH C:\xampp\htdocs\tour\resources\views\admin\tour-packages\partials\pricing\selector.blade.php ENDPATH**/ ?>